import { SavingsAccount } from "@prisma/client";
import styles from "./index.module.css";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.showcaseContainer}>
            <AuthShowcase />
            <AccountList />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  
  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

const AccountList: React.FC = () => {
  const { data: sessionData } = useSession();
  const { mutate } = api.dave.createSavingsAccount.useMutation({
    onSucces: () => {
      console.log("account created");
      void null;
    }
  })
  const { data: myAccounts } = api.dave.getAllSavingsAccount.useQuery();
  return (
    <>
      <p>Accounts</p>
      { myAccounts?.map( (account: SavingsAccount) => (
        <div key={account.id}>{account?.name} - {account?.location}</div>
      ))}
      <>
        <p>Add account</p>
        
      </>
    </>
  )
}